# Generated by Django 4.0.1 on 2022-02-06 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WordleColourResult', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphicTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wordleresult', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WordleColourResult.wordleresult')),
            ],
        ),
    ]
