# Generated by Django 4.0.1 on 2022-02-16 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WordleColourResult', '0002_graphictable'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphictable',
            name='answer',
            field=models.CharField(choices=[('G', 'Green'), ('Y', 'Yellow'), ('B', 'Black')], default='B', max_length=1),
        ),
    ]
