# Generated by Django 4.0.1 on 2022-02-23 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WordleColourResult', '0005_wordleresult_simple_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordleresult',
            name='letter_table',
            field=models.CharField(default='BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB', max_length=30),
        ),
    ]
