# Generated by Django 4.0.1 on 2022-02-23 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WordleColourResult', '0006_wordleresult_letter_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordleresult',
            name='letter_table',
            field=models.CharField(default='BBBBBEBBBBBEBBBBBEBBBBBEBBBBBEBBBBB', max_length=35),
        ),
    ]
