# Generated by Django 4.0.1 on 2022-06-20 21:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WordleColourResult', '0009_alter_userresult_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresult',
            name='date_update',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
