# Generated by Django 4.0.1 on 2022-06-20 22:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WordleColourResult', '0010_userresult_date_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresult',
            name='time_update',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
