# Generated by Django 4.0.1 on 2022-06-24 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WordleColourResult', '0012_dateresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealUserResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_date', models.DateField()),
                ('result_time', models.TimeField()),
                ('result_letters', models.CharField(default='BBBBBEBBBBBEBBBBBEBBBBBEBBBBBEBBBBB', max_length=35)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
